version: '3'
services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    image: playwright-tests
    volumes:
      - ./packages:/dev/packages
    ports:
      - '5713:5713'
    working_dir: /dev
